name: 'squads-multisig-program-upgrade'
description: 'Get started with Container actions'
author: '0x'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
branding:
  icon: 'award'
  color: 'green'
